### ISSUE TITLE
Error when running `skill_discovery.py`

### ISSUE THREAD

**Issue by hhhsu-cmlab** [real-stanford/xskill#5]
Hello, thank you for this research! I got the following error when running `python scripts/realworld/skill_discovery.py`:
```
output_dir: /home/hanyuan/Desktop/xskill/None/xskill/experiment/pretrain/2024-01-17_15-04-49
['None/xskill/datasets/realworld_kitchen_dataset/data_v2/draw_cloth_light', 'None/xskill/datasets/realworld_kitchen_dataset/data_v2/draw_light_cloth', 'None/xskill/datasets/realworld_kitchen_dataset/data_v2/draw_light_oven', 'None/xskill/datasets/realworld_kitchen_dataset/data_v2/light_cloth_oven', 'None/xskill/datasets/realworld_kitchen_dataset/data_v2/light_draw_cloth', 'None/xskill/datasets/realworld_kitchen_dataset/data_v2/light_oven_draw', 'None/xskill/datasets/realworld_kitchen_dataset/data_v2/oven_light_cloth']
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/home/hanyuan/Desktop/xskill/xskill/dataset/real_world_pretrain_dataset.py", line 36, in __init__
    self.in_replay_buffer = {
  File "/home/hanyuan/Desktop/xskill/xskill/dataset/real_world_pretrain_dataset.py", line 37, in <dictcomp>
    dir: real_data_to_replay_buffer(dir,
  File "/home/hanyuan/Desktop/xskill/xskill/dataset/real_data_conversion.py", line 59, in real_data_to_replay_buffer
    assert in_zarr_path.is_dir()
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hanyuan/Desktop/xskill/scripts/realworld/skill_discovery.py", line 67, in <module>
    pretrain()
  File "/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/hanyuan/Desktop/xskill/scripts/realworld/skill_discovery.py", line 20, in pretrain
    robot_dataset = hydra.utils.instantiate(cfg.robot_dataset)
  File "/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'xskill.dataset.real_world_pretrain_dataset.RealWorldEpisodeTrajDataset':
AssertionError()
full_key: robot_dataset
```

**Comment by mengdaxu** [comment]
Hi,
I believe you pass the wrong path into the config file: /home/hanyuan/Desktop/xskill/**None**/xskill/experiment/pretrain/2024-01-17_15-04-49.

**Comment by hhhsu-cmlab** [comment]
Thank you for your reply! I have changed the `base_dev_dir` in all the config files to be `'~/Desktop/xskill'`, which is where I store this repository locally. Then, when I run
```
cd scripts
python create_all_kitchen_dataset.py
```
I still get the same error as follows: 
```
0it [00:00, ?it/s]
Reading configurations for Franka
Initializing Franka sim
0it [00:00, ?it/s]
Reading configurations for Franka
Initializing Franka sim
0it [00:00, ?it/s]
Reading configurations for Franka
Initializing Franka sim
0it [00:00, ?it/s]
Reading configurations for Franka
Initializing Franka sim
0it [00:00, ?it/s]
Reading configurations for Franka
Initializing Franka sim
0it [00:00, ?it/s]
Reading configurations for Franka
Initializing Franka sim
0it [00:00, ?it/s]
Reading configurations for Franka
Initializing Franka sim
0it [00:00, ?it/s]
Reading configurations for Franka
Initializing Franka sim
/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
  0%|                                                                                                                                          | 0/61 [00:00<?, ?it/s]
Error executing job with overrides: ['start_eps=305', 'end_eps=366', 'embodiment=robot']
Traceback (most recent call last):
  File "/home/hanyuan/Desktop/xskill/scripts/create_kitchen_dataset.py", line 35, in create_dataset
    eps_data = kitchen_dataset.replay_buffer.get_episode(eps_idx)
  File "/home/hanyuan/Desktop/xskill/xskill/common/replay_buffer.py", line 531, in get_episode
    idx = list(range(len(self.episode_ends)))[idx]
IndexError: list index out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
  0%|                                                                                                                                          | 0/61 [00:00<?, ?it/s]
Error executing job with overrides: ['start_eps=0', 'end_eps=61', 'embodiment=robot']
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/hanyuan/Desktop/xskill/scripts/create_kitchen_dataset.py", line 35, in create_dataset
    eps_data = kitchen_dataset.replay_buffer.get_episode(eps_idx)
  File "/home/hanyuan/Desktop/xskill/xskill/common/replay_buffer.py", line 531, in get_episode
    idx = list(range(len(self.episode_ends)))[idx]
IndexError: list index out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Reading configurations for Franka
Initializing Franka sim
/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
  0%|                                                                                                                                          | 0/61 [00:00<?, ?it/s]
Error executing job with overrides: ['start_eps=488', 'end_eps=549', 'embodiment=robot']
Traceback (most recent call last):
  File "/home/hanyuan/Desktop/xskill/scripts/create_kitchen_dataset.py", line 35, in create_dataset
    eps_data = kitchen_dataset.replay_buffer.get_episode(eps_idx)
  File "/home/hanyuan/Desktop/xskill/xskill/common/replay_buffer.py", line 531, in get_episode
    idx = list(range(len(self.episode_ends)))[idx]
IndexError: list index out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
  0%|                                                                                                                                          | 0/61 [00:00<?, ?it/s]
Error executing job with overrides: ['start_eps=183', 'end_eps=244', 'embodiment=robot']
Traceback (most recent call last):
  File "/home/hanyuan/Desktop/xskill/scripts/create_kitchen_dataset.py", line 35, in create_dataset
    eps_data = kitchen_dataset.replay_buffer.get_episode(eps_idx)
  File "/home/hanyuan/Desktop/xskill/xskill/common/replay_buffer.py", line 531, in get_episode
    idx = list(range(len(self.episode_ends)))[idx]
IndexError: list index out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
0it [00:00, ?it/s]
Reading configurations for Franka
Initializing Franka sim
/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
  0%|                                                                                                                                          | 0/61 [00:00<?, ?it/s]
Error executing job with overrides: ['start_eps=366', 'end_eps=427', 'embodiment=robot']
Traceback (most recent call last):
  File "/home/hanyuan/Desktop/xskill/scripts/create_kitchen_dataset.py", line 35, in create_dataset
    eps_data = kitchen_dataset.replay_buffer.get_episode(eps_idx)
  File "/home/hanyuan/Desktop/xskill/xskill/common/replay_buffer.py", line 531, in get_episode
    idx = list(range(len(self.episode_ends)))[idx]
IndexError: list index out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
  0%|                                                                                                                                          | 0/61 [00:00<?, ?it/s]
Error executing job with overrides: ['start_eps=244', 'end_eps=305', 'embodiment=robot']
Traceback (most recent call last):
  File "/home/hanyuan/Desktop/xskill/scripts/create_kitchen_dataset.py", line 35, in create_dataset
    eps_data = kitchen_dataset.replay_buffer.get_episode(eps_idx)
  File "/home/hanyuan/Desktop/xskill/xskill/common/replay_buffer.py", line 531, in get_episode
    idx = list(range(len(self.episode_ends)))[idx]
IndexError: list index out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
  0%|                                                                                                                                          | 0/61 [00:00<?, ?it/s]
Error executing job with overrides: ['start_eps=61', 'end_eps=122', 'embodiment=robot']
Traceback (most recent call last):
  File "/home/hanyuan/Desktop/xskill/scripts/create_kitchen_dataset.py", line 35, in create_dataset
    eps_data = kitchen_dataset.replay_buffer.get_episode(eps_idx)
  File "/home/hanyuan/Desktop/xskill/xskill/common/replay_buffer.py", line 531, in get_episode
    idx = list(range(len(self.episode_ends)))[idx]
IndexError: list index out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
  0%|                                                                                                                                          | 0/61 [00:00<?, ?it/s]
Error executing job with overrides: ['start_eps=122', 'end_eps=183', 'embodiment=robot']
Traceback (most recent call last):
  File "/home/hanyuan/Desktop/xskill/scripts/create_kitchen_dataset.py", line 35, in create_dataset
    eps_data = kitchen_dataset.replay_buffer.get_episode(eps_idx)
  File "/home/hanyuan/Desktop/xskill/xskill/common/replay_buffer.py", line 531, in get_episode
    idx = list(range(len(self.episode_ends)))[idx]
IndexError: list index out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
  0%|                                                                                                                                          | 0/54 [00:00<?, ?it/s]
Error executing job with overrides: ['start_eps=549', 'end_eps=603', 'embodiment=robot']
Traceback (most recent call last):
  File "/home/hanyuan/Desktop/xskill/scripts/create_kitchen_dataset.py", line 35, in create_dataset
    eps_data = kitchen_dataset.replay_buffer.get_episode(eps_idx)
  File "/home/hanyuan/Desktop/xskill/xskill/common/replay_buffer.py", line 531, in get_episode
    idx = list(range(len(self.episode_ends)))[idx]
IndexError: list index out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
  0%|                                                                                                                                          | 0/61 [00:00<?, ?it/s]
Error executing job with overrides: ['start_eps=427', 'end_eps=488', 'embodiment=robot']
Traceback (most recent call last):
  File "/home/hanyuan/Desktop/xskill/scripts/create_kitchen_dataset.py", line 35, in create_dataset
    eps_data = kitchen_dataset.replay_buffer.get_episode(eps_idx)
  File "/home/hanyuan/Desktop/xskill/xskill/common/replay_buffer.py", line 531, in get_episode
    idx = list(range(len(self.episode_ends)))[idx]
IndexError: list index out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
0it [00:00, ?it/s]
Reading configurations for Franka
Initializing Franka sim
0it [00:00, ?it/s]
Reading configurations for Franka
Initializing Franka sim
0it [00:00, ?it/s]
Reading configurations for Franka
Initializing Franka sim
0it [00:00, ?it/s]
Reading configurations for Franka
Initializing Franka sim
0it [00:00, ?it/s]
Reading configurations for Franka
Initializing Franka sim
0it [00:00, ?it/s]
Reading configurations for Franka
Initializing Franka sim
0it [00:00, ?it/s]
Reading configurations for Franka
Initializing Franka sim
0it [00:00, ?it/s]
Reading configurations for Franka
Initializing Franka sim
0it [00:00, ?it/s]
Reading configurations for Franka
Initializing Franka sim
0it [00:00, ?it/s]
Reading configurations for Franka
Initializing Franka sim
/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
  0%|                                                                                                                                          | 0/61 [00:00<?, ?it/s]
Error executing job with overrides: ['start_eps=427', 'end_eps=488', 'embodiment=human']
/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
  0%|                                                                                                                                          | 0/61 [00:00<?, ?it/s]
Error executing job with overrides: ['start_eps=488', 'end_eps=549', 'embodiment=human']
Traceback (most recent call last):
  File "/home/hanyuan/Desktop/xskill/scripts/create_kitchen_dataset.py", line 35, in create_dataset
    eps_data = kitchen_dataset.replay_buffer.get_episode(eps_idx)
  File "/home/hanyuan/Desktop/xskill/xskill/common/replay_buffer.py", line 531, in get_episode
    idx = list(range(len(self.episode_ends)))[idx]
IndexError: list index out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Traceback (most recent call last):
  File "/home/hanyuan/Desktop/xskill/scripts/create_kitchen_dataset.py", line 35, in create_dataset
    eps_data = kitchen_dataset.replay_buffer.get_episode(eps_idx)
  File "/home/hanyuan/Desktop/xskill/xskill/common/replay_buffer.py", line 531, in get_episode
    idx = list(range(len(self.episode_ends)))[idx]
IndexError: list index out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
  0%|                                                                                                                                          | 0/61 [00:00<?, ?it/s]
Error executing job with overrides: ['start_eps=183', 'end_eps=244', 'embodiment=human']
Traceback (most recent call last):
  File "/home/hanyuan/Desktop/xskill/scripts/create_kitchen_dataset.py", line 35, in create_dataset
    eps_data = kitchen_dataset.replay_buffer.get_episode(eps_idx)
  File "/home/hanyuan/Desktop/xskill/xskill/common/replay_buffer.py", line 531, in get_episode
    idx = list(range(len(self.episode_ends)))[idx]
IndexError: list index out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
  0%|                                                                                                                                          | 0/61 [00:00<?, ?it/s]
Error executing job with overrides: ['start_eps=122', 'end_eps=183', 'embodiment=human']
Traceback (most recent call last):
  File "/home/hanyuan/Desktop/xskill/scripts/create_kitchen_dataset.py", line 35, in create_dataset
    eps_data = kitchen_dataset.replay_buffer.get_episode(eps_idx)
  File "/home/hanyuan/Desktop/xskill/xskill/common/replay_buffer.py", line 531, in get_episode
    idx = list(range(len(self.episode_ends)))[idx]
IndexError: list index out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
  0%|                                                                                                                                          | 0/61 [00:00<?, ?it/s]
Error executing job with overrides: ['start_eps=61', 'end_eps=122', 'embodiment=human']
Traceback (most recent call last):
  File "/home/hanyuan/Desktop/xskill/scripts/create_kitchen_dataset.py", line 35, in create_dataset
    eps_data = kitchen_dataset.replay_buffer.get_episode(eps_idx)
  File "/home/hanyuan/Desktop/xskill/xskill/common/replay_buffer.py", line 531, in get_episode
    idx = list(range(len(self.episode_ends)))[idx]
IndexError: list index out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
  0%|                                                                                                                                          | 0/54 [00:00<?, ?it/s]
Error executing job with overrides: ['start_eps=549', 'end_eps=603', 'embodiment=human']
/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
  0%|                                                                                                                                          | 0/61 [00:00<?, ?it/s]
Error executing job with overrides: ['start_eps=366', 'end_eps=427', 'embodiment=human']
Traceback (most recent call last):
  File "/home/hanyuan/Desktop/xskill/scripts/create_kitchen_dataset.py", line 35, in create_dataset
    eps_data = kitchen_dataset.replay_buffer.get_episode(eps_idx)
  File "/home/hanyuan/Desktop/xskill/xskill/common/replay_buffer.py", line 531, in get_episode
    idx = list(range(len(self.episode_ends)))[idx]
IndexError: list index out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Traceback (most recent call last):
  File "/home/hanyuan/Desktop/xskill/scripts/create_kitchen_dataset.py", line 35, in create_dataset
    eps_data = kitchen_dataset.replay_buffer.get_episode(eps_idx)
  File "/home/hanyuan/Desktop/xskill/xskill/common/replay_buffer.py", line 531, in get_episode
    idx = list(range(len(self.episode_ends)))[idx]
IndexError: list index out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
  0%|                                                                                                                                          | 0/61 [00:00<?, ?it/s]
Error executing job with overrides: ['start_eps=244', 'end_eps=305', 'embodiment=human']
Traceback (most recent call last):
  File "/home/hanyuan/Desktop/xskill/scripts/create_kitchen_dataset.py", line 35, in create_dataset
    eps_data = kitchen_dataset.replay_buffer.get_episode(eps_idx)
  File "/home/hanyuan/Desktop/xskill/xskill/common/replay_buffer.py", line 531, in get_episode
    idx = list(range(len(self.episode_ends)))[idx]
IndexError: list index out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
  0%|                                                                                                                                          | 0/61 [00:00<?, ?it/s]
Error executing job with overrides: ['start_eps=0', 'end_eps=61', 'embodiment=human']
Traceback (most recent call last):
  File "/home/hanyuan/Desktop/xskill/scripts/create_kitchen_dataset.py", line 35, in create_dataset
    eps_data = kitchen_dataset.replay_buffer.get_episode(eps_idx)
  File "/home/hanyuan/Desktop/xskill/xskill/common/replay_buffer.py", line 531, in get_episode
    idx = list(range(len(self.episode_ends)))[idx]
IndexError: list index out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
/home/hanyuan/anaconda3/envs/xskill/lib/python3.9/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
  0%|                                                                                                                                          | 0/61 [00:00<?, ?it/s]
Error executing job with overrides: ['start_eps=305', 'end_eps=366', 'embodiment=human']
Traceback (most recent call last):
  File "/home/hanyuan/Desktop/xskill/scripts/create_kitchen_dataset.py", line 35, in create_dataset
    eps_data = kitchen_dataset.replay_buffer.get_episode(eps_idx)
  File "/home/hanyuan/Desktop/xskill/xskill/common/replay_buffer.py", line 531, in get_episode
    idx = list(range(len(self.episode_ends)))[idx]
IndexError: list index out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

When I run `python scripts/realworld/skill_discovery.py`, this is the error message I get:
```
output_dir: /home/hanyuan/Desktop/xskill/~/Desktop/xskill/xskill/experiment/pretrain/2024-01-18_09-20-06
['~/Desktop/xskill/xskill/datasets/realworld_kitchen_dataset/data_v2/draw_cloth_light', '~/Desktop/xskill/xskill/datasets/realworld_kitchen_dataset/data_v2/draw_light_cloth', '~/Desktop/xskill/xskill/datasets/realworld_kitchen_dataset/data_v2/draw_light_oven', '~/Desktop/xskill/xskill/datasets/realworld_kitchen_dataset/data_v2/light_cloth_oven', '~/Desktop/xskill/xskill/datasets/realworld_kitchen_dataset/data_v2/light_draw_cloth', '~/Desktop/xskill/xskill/datasets/realworld_kitchen_dataset/data_v2/light_oven_draw', '~/Desktop/xskill/xskill/datasets/realworld_kitchen_dataset/data_v2/oven_light_cloth']
Error executing job with overrides: []
Error in call to target 'xskill.dataset.real_world_pretrain_dataset.RealWorldEpisodeTrajDataset':
AssertionError()
full_key: robot_dataset

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

My OS is Ubuntu 20.04 by the way. Also, I have extracted both the simulation and the real world datasets, and here is the directory tree of the datasets folder up to depth 2, if this information is helpful:
```
.
├── data_v2
│   ├── draw_cloth_light
│   ├── draw_cloth_oven
│   ├── draw_light_cloth
│   ├── draw_light_oven
│   ├── human_cloth_light_oven
│   ├── human_cloth_oven_light
│   ├── human_draw_cloth_light
│   ├── human_draw_cloth_oven
│   ├── human_draw_light_cloth
│   ├── human_draw_light_oven
│   ├── human_light_cloth_oven
│   ├── human_oven_draw_cloth
│   ├── light_cloth_oven
│   ├── light_draw_cloth
│   ├── light_oven_draw
│   └── oven_light_cloth
├── kitchen
│   ├── actions_seq.npy
│   ├── all_actions.npy
│   ├── all_init_qpos.npy
│   ├── all_init_qvel.npy
│   ├── all_observations.npy
│   ├── existence_mask.npy
│   ├── kitchen_demos_multitask
│   └── observations_seq.npy
├── kitchen.zip
└── real_kitchen_data.zip
```

**Comment by Ram-Raghav-S** [comment]
Did you end up figuring out the issue? I am running into the same IndexError.

Edit: nvm - was passing in the wrong base_dev_dir
